# Numpy
- Library to handle arrays.
- numpy arrays are non resizeable (can't append or remove elements)
- much faster than Pythons dynamically typed lists
- supports use of vector operations (man kan snabbt utföra operationer på arrayer, på ett sätt man inte kan på listor.)
- Numpy använder statiskt typade typer. Python i vanliga fall är dynamiskt typat.
- statically typed: element can't be mixed or altered.
- arrayer kan inte blanda olika datatyper, dvs den behöver inte kolla vad varje element i en array är för något => snabbare och kräver mindre minne
- Att hantera dynamiska datatyper, såsom listor och listor med dictionarys mm, kostar mer energi.
- Man kan ange vilken datatyp en array ska ha.
- Skapa array:
1. np.array()-metoden med en lista som input.
2. np.random.random(nbr), med nbr som anger antal
3. np.zeros()
4. np.ones()
- np.shape() för att få ut storleken på en array.
- man kan använda en lista av index för att få ut värden ur en array


In [7]:
import numpy as np
my_array = np.array([5, 2, 6, 8])
my_array2 = np.array([5, 2, 6, 8.0])
my_array3 = np.array([1,2,3], dtype = float) # det går att ange datatyp


print(my_array)
my_array.dtype
my_array2.dtype

[5 2 6 8]


dtype('float64')

In [10]:
a2 = np.random.random(20) # vektor med 20 värden mellan 0 och 1
print(a2)
a3=np.random.randint(10,20, 5) # start, slut, antal
print(a3)


[0.11972081 0.33533452 0.79372044 0.03097003 0.37082812 0.82854973
 0.91704054 0.15272861 0.28571813 0.19737794 0.48563377 0.60299786
 0.14609246 0.82108866 0.08898841 0.03150155 0.15422062 0.34356263
 0.17598143 0.73183353]
[18 13 18 17 10]


In [17]:
a4 = np.zeros(10)
print(a4)
a5 = np.ones(12)
print(a5)
a6 = np.linspace(0, 100, 101)
print(a6)
a7 = np.arange(0,10,0.1)
print(a7)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100.]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


# Vectorized Operations
- I numpy kan man enkelt göra operationer på hela vektorer, på alla element i arrayen samtidigt
- man slipper göra nya listor tex.
- math biblioteket kan bara göra operationer på skalärer
- 

In [19]:
# vanliga python
x = [2, 3, 4, 5, 7, 5, 9, 3, 0, 2] # lista med random värden
print(x)
#x * 2
x = [value * 2 for value in x]
print(x)


[2, 3, 4, 5, 7, 5, 9, 3, 0, 2]
[4, 6, 8, 10, 14, 10, 18, 6, 0, 4]


In [23]:
# numpy :)
x = np.array([2, 3, 4, 5, 7, 5, 9, 3, 0, 2])
print(x)
x = x * 2 + 1
print(x)
print(np.sqrt(x))



[2 3 4 5 7 5 9 3 0 2]
[ 5  7  9 11 15 11 19  7  1  5]
[2.23606798 2.64575131 3.         3.31662479 3.87298335 3.31662479
 4.35889894 2.64575131 1.         2.23606798]


In [27]:
a = np.array([5, 9, 3, 0, 2])
b = np.array([2, 3, 4, 5, 7])

print(a+b)
print(a*b)
print(np.sqrt(a**2 + b**2)) # pythagoras sats på alla kateter

print(a.shape)

[ 7 12  7  5  9]
[10 27 12  0 14]
[5.38516481 9.48683298 5.         5.         7.28010989]
(5,)


# Array indexing and slicing
- indexing och slicing funkar på samma sätt som med listor.
- man kan använda en lista av index för att få ut värden ur en array
- man kan skicka in en lista med booleans för att skapa en ny array (boolean mask / boolean indexing)
- numpy har en inbyggd funktiom för att skapa sin lista med booleans
- Dessa kan användas för att filtrera i en numpy array

In [41]:
x = np.array([2, 3, 4, 5, 7, 5, 9, 3, 0, 2])
x
print(x == 2) # boolean indexing
x[x==2] # får ut alla 2-or, funkar också med andra jämförelse operationer > < etc


[ True False False False False False False False False  True]


array([2, 2])

In [38]:
print(x[-1])
print(x[1])
print(x[:3])
print(x[[0, 0, -1, 3, 0]]) # filtering using a list of indices
print(x[[True, False, False, True, True, True, False, True, False, True]]) # boolean indexing

2
3
[2 3 4]
[2 2 2 5 2]
[2 5 7 5 3 2]


# Aggregation methods
- An aggregation method is a method that takes a list / array of values and by doing some calculations returning a single value.
- 

In [42]:
x = np.array([2, 3, 4, 5, 7, 5, 9, 3, 0, 2])
x

array([2, 3, 4, 5, 7, 5, 9, 3, 0, 2])

In [48]:
print(f'{np.sum(x) = }')
print(f'{x.sum() = }')

print(f'{np.min(x) = }')
print(f'{np.max(x) = }')
print(f'{np.mean(x) = }')
print(f'{np.std(x) = }')

np.sum(x) = 40
x.sum() = 40
np.min(x) = 0
np.max(x) = 9
np.mean(x) = 4.0
np.std(x) = 2.4899799195977463


# Multidimensional arrays

In [ ]:
x_1d = np.array([2, 3, 4, 5, 7, 5, 9, 3, 0, 2])

In [49]:
x_2d = np.array([[2, 3, 4, 5, 7],[5, 9, 3, 0, 2]])
x_2d

array([[2, 3, 4, 5, 7],
       [5, 9, 3, 0, 2]])

In [51]:
random_2d = np.random.randint(0, 10, [5, 4])
random_2d

array([[6, 7, 7, 7],
       [4, 8, 4, 9],
       [2, 3, 1, 1],
       [6, 7, 9, 1],
       [6, 9, 7, 5]])

In [52]:
random_3d = np.random.randint(0, 10, [2, 5, 4])
random_3d

array([[[6, 1, 8, 8],
        [3, 5, 6, 9],
        [5, 6, 4, 8],
        [0, 2, 6, 4],
        [4, 1, 7, 8]],

       [[2, 0, 2, 4],
        [6, 7, 6, 2],
        [5, 3, 8, 2],
        [5, 4, 2, 0],
        [9, 2, 3, 2]]])

## Indexing and slizing of 2d arrays


In [60]:
# indexing in 2d array
random_2d = np.random.randint(0, 10, [5, 4])
print(random_2d)
print(random_2d[0])
print(random_2d[0][-1])
print(random_2d[0, -1]) # ger samma som ovan

[[3 1 3 8]
 [4 9 8 6]
 [9 5 7 7]
 [9 3 2 9]
 [4 0 8 4]]
[3 1 3 8]
8
8


In [64]:
# slizing in 2d array
random_2d = np.random.randint(0, 10, [5, 4])
print(random_2d)
print(random_2d[:, 1])
print(random_2d[:3,1:])

[[1 1 9 0]
 [8 1 7 6]
 [0 9 8 3]
 [9 7 9 1]
 [0 4 7 5]]
[1 1 9 7 4]
[[1 9 0]
 [1 7 6]
 [9 8 3]]
